name = "Pigeon"
uuid = "5feeeddc-254b-4aab-a0bc-ed990ddc1d92"
authors = ["Peter Ahrens"]
version = "0.1.0"

[deps]
Lerche = "d42ef402-04e6-4356-9f73-091573ea58dc"
SymbolicUtils = "d1185830-fcd6-423d-90d6-eec64667417b"

[compat]
SymbolicUtils = "0.16"
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
